# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ArtdatabankenDialog
                                 A QGIS plugin
 Getting data from Artdatabanken
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-20
        git sha              : $Format:%H$
        copyright            : (C) 2024 by LU
        email                : 00albabj@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtWidgets import QDialog, QCheckBox
from qgis.core import QgsProject, QgsWkbTypes, QgsVectorLayer
from PyQt5.QtCore import QDate


# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
AREA_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Area_Search.ui'))

FIRST_POP, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'First_pop_up.ui'))

SPECIES_TYPE, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Species_search.ui'))


WFS_INFO, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'WFS_attributes.ui'))

WFS_SEARCH, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'WFS_search.ui'))

SPECIES_ATT, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Species_attributes.ui'))

# class for Area, adding the UI and working checkboxes, and options to select/clear all
class ArtdatabankenDialog(QtWidgets.QDialog, AREA_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(ArtdatabankenDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.selectAll.clicked.connect(self.select_all)
        self.clearAll.clicked.connect(self.clear_all)
        self.maxNbr_area.setText("10")

        # Find all checkboxes (assuming they are within a specific container)
        self.checkboxes = self.findChildren(QCheckBox)

    def select_all(self):
        for checkbox in self.checkboxes:
            checkbox.setChecked(True)

    def clear_all(self):
        for checkbox in self.checkboxes:
            checkbox.setChecked(False)

# class for first pop-up to load in the UI
class FirstPopupDialog(QtWidgets.QDialog, FIRST_POP):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)


# class for Species first page for options
class ArtTypeDialog(QtWidgets.QDialog, SPECIES_TYPE):
    def __init__(self, parent=None):
        super(ArtTypeDialog, self).__init__(parent)
        self.setupUi(self)

        self.startDate = self.findChild(QtWidgets.QDateEdit, 'startDate')
        self.endDate = self.findChild(QtWidgets.QDateEdit, 'endDate')

        self.startDate.setDate(QDate(1900, 1, 1))
        self.endDate.setDate(QDate(2025, 1, 1))
        self.maxNbr_art.setText("10")

# class for Species attribute, adding the UI and working checkboxes, and options to select/clear all
class ArtAttDialog(QtWidgets.QDialog, SPECIES_ATT):
    def __init__(self, parent=None):
        super(ArtAttDialog, self).__init__(parent)
        self.setupUi(self)
        self.selectAll.clicked.connect(self.select_all)
        self.clearAll.clicked.connect(self.clear_all)

        # Find all checkboxes (assuming they are within a specific container)
        self.checkboxes = self.findChildren(QCheckBox)

    def select_all(self):
        for checkbox in self.checkboxes:
            checkbox.setChecked(True)

    def clear_all(self):
        for checkbox in self.checkboxes:
            checkbox.setChecked(False)

# class for WFS first pop-up for overall options
class WFSSearchDialog(QtWidgets.QDialog, WFS_SEARCH):
    def __init__(self, parent=None):
        super(WFSSearchDialog, self).__init__(parent)
        self.setupUi(self)

        # Add start- and end-date as variables
        self.startDate = self.findChild(QtWidgets.QDateEdit, 'startDate')
        self.endDate = self.findChild(QtWidgets.QDateEdit, 'endDate')

        self.startDate.setDate(QDate(1900, 1, 1))
        self.endDate.setDate(QDate(2025, 1, 1))
        self.maxNbr_WFS.setText("10")

        # Populate polygon layer combo box
        self.polygonLayerComboBox.addItem("No polygon")
        polygon_layers = [
            layer.name()
            for layer in QgsProject.instance().mapLayers().values()
            if isinstance(layer, QgsVectorLayer) and layer.geometryType() == QgsWkbTypes.PolygonGeometry
        ]
        self.polygonLayerComboBox.addItems(polygon_layers)

class WFSInfoDialog(QtWidgets.QDialog, WFS_INFO):
    def __init__(self, parent=None):
        super(WFSInfoDialog, self).__init__(parent)
        self.setupUi(self)
        self.selectAll.clicked.connect(self.select_all)
        self.clearAll.clicked.connect(self.clear_all)

        # Find all checkboxes (assuming they are within a specific container)
        self.checkboxes = self.findChildren(QCheckBox)

    def select_all(self):
        for checkbox in self.checkboxes:
            checkbox.setChecked(True)

    def clear_all(self):
        for checkbox in self.checkboxes:
            checkbox.setChecked(False)